class Quets{
  static List<Quets>getQuets()=>[
    Quets("Success usually comes to those who are too busy to be looking for it."," Henry David Thoreau"),
    Quets("If you are not willing to risk the usual, you will have to settle for the ordinary.","n Jim Rohn"),
    Quets("Take up one idea. Make that one idea your life-think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success."," Swami Vivekananda"),
    Quets("If you are willing to do more than you are paid to do, eventually you will be paid to do more than you do.","Anonymous"),
    Quets("Success is walking from failure to failure with no loss of enthusiasm."," Winston Churchill"),
    Quets("Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them.","Vaibhav Shah"),
    Quets("Try not to become a person of success, but rather try to become a person of value."," Albert Einstein"),
    Quets("It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change."," Charles Darwin"),
    Quets("Great minds discuss ideas; average minds discuss events; small minds discuss people."," Eleanor Roosevelt"),
    Quets("No one can make you feel inferior without your consent."," Eleanor Roosevelt"),
    Quets("The distance between insanity and genius is measured only by success."," Bruce Feirstein"),
    Quets("Don't be afraid to give up the good to go for the great."," John D. Rockefeller"),
    Quets("If you can't explain it simply, you don't understand it well enough."," Albert Einstein"),
    Quets("There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed."," Ray Goforth"),
    Quets("Success is the sum of small efforts, repeated day in and day out."," Robert Collier"),
    Quets("Courage is resistance to fear, mastery of fear -- not absence of fear."," Mark Twain"),
    Quets("Only put off until tomorrow what you are willing to die having left undone."," Pablo Picasso"),
    Quets("Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover."," Mark Twain"),
    Quets("The successful warrior is the average man, with laserlike focus."," Bruce Lee"),
    Quets("You can't connect the dots looking forward; you can only connect them looking backward. So you have to trust that the dots will somehow connect in your future. You have to trust in something -- your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life."," Steve Jobs"),
    Quets("Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better."," Jim Rohn"),
    Quets("The No. 1 reason people fail in life is because they listen to their friends, family, and neighbors."," Napoleon Hill"),
    Quets("You may have to fight a battle more than once to win it."," Margaret Thatcher"),
    Quets("Many of life's failures are people who did not realize how close they were to success when they gave up."," Thomas A. Edison"),
    Quets("What would you attempt to do if you knew you would not fail?","Robert Schuller"),
    Quets("Always bear in mind that your own resolution to success is more important than any other one thing."," Abraham Lincoln"),
    Quets("Successful and unsuccessful people do not vary greatly in their abilities. They vary in their desires to reach their potential."," John Maxwell"),
    Quets("I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel."," Maya Angelou"),
    Quets("Much of the stress that people feel doesn't come from having too much to do. It comes from not finishing what they've started."," David Allen"),
    Quets("Focus on the journey, not the destination. Joy is found not in finishing an activity but in doing it.","Greg Anderson"),
    Quets("You never regret being kind.","Nicole Shepherd"),
    Quets("Success at the highest level comes down to one question: Can you decide that your happiness can come from someone else's success?","Bill Walton"),
    Quets("Do what you have always done and you'll get what you have always got.", "Sue Knight"),
    Quets("Think of what you have rather than of what you lack. Of the things you have, select the best and then reflect how eagerly you would have sought them if you did not have them.","Marcus Aurelius"),
    Quets("Happiness is where we find it, but very rarely where we seek it.", "J. Petit Senn"),
    Quets("To be content means that you realize you contain what you seek.","Alan Cohen"),
    Quets("Expecting life to treat you well because you are a good person is like expecting an angry bull not to charge because you are a vegetarian." ,"Shari R. Barr"),
    Quets("View your life from your funeral: Looking back at your life experiences, what have you accomplished? What would you have wanted to accomplish but didn't? What were the happy moments? What were the sad? What would you do again, and what wouldn't you do?"," Victor Frankl"),
    Quets("Boredom is the feeling that everything is a waste of time...serenity, that nothing is."," Thomas Szasz"),
    Quets("To handle yourself, use your head; to handle others, use your heart."," Eleanor Roosevelt"),
    Quets("The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires."," William Arthur Ward"),
    Quets("Keep your fears to yourself, but share your courage with others." ,"Robert Louis Stevenson"),
    Quets("The greatest leader is not necessarily the one who does the greatest things. He is the one that gets people to do the greatest things."," Ronald Reagan"),
    Quets("Power isn't control at all-power is strength, and giving that strength to others. A leader isn't someone who forces others to make him stronger; a leader is someone willing to give his strength to others that they may have the strength to stand on their own."," Beth Revis"),
    Quets("Don't tell people how to do things; tell them what to do and let them surprise you with their results."," George S. Patton Jr."),
    Quets("Leadership is the art of getting someone else to do something you want done because he wants to do it."," Dwight D. Eisenhower"),
    Quets("Victory has a hundred fathers and defeat is an orphan."," John F. Kennedy"),
    Quets("Management is doing things right; leadership is doing the right things."," Peter F. Drucker"),
    Quets("Example is not the main thing in influencing others. It is the only thing."," Albert Schweitzer"),
    Quets("Leaders must be close enough to relate to others, but far enough ahead to motivate them.", "John C. Maxwell"),
    Quets("The mark of a great man is one who knows when to set aside the important things in order to accomplish the vital ones."," Brandon Sanderson"),
    Quets("Leadership is not about titles, positions, or flowcharts. It is about one life influencing another."," John C. Maxwell"),
    Quets("You have to be burning with an idea, or a problem, or a wrong that you want to right. If you're not passionate enough from the start, you'll never stick it out."," Steve Jobs"),
    Quets("A leader ... is like a shepherd. He stays behind the flock, letting the most nimble go out ahead, whereupon the others follow, not realizing that all along they are being directed from behind."," Nelson Mandela"),
    Quets("Being responsible sometimes means pissing people off."," Colin Powell"),
    Quets("Do you know that one of the great problems of our age is that we are governed by people who care more about feelings than they do about thoughts and ideas."," Margaret Thatcher"),
    Quets("A leader is a dealer in hope."," Napoleon"),
    Quets("The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint to keep om meddling with them while they do it."," Theodore Roosevelt"),
    Quets("If you would convince a man that he does wrong, do right. But do not care to convince him. Men will believe what they see. Let them see."," Henry David Thoreau"),
    Quets("I cannot trust a man to control others who cannot control himself."," Robert E. Lee"),
    Quets("Consensus: the process of abandoning all beliefs, principles, values, and policies in search of something in which no one believes, but to which no one objects; the process of avoiding the very issues that have to be solved, merely because you cannot get agreement on the way ahead. What great cause would have been fought and won under the banner: 'I stand for consensus?'"," Margaret Thatcher"),
    Quets("A leader takes people where they want to go. A great leader takes people where they don't necessarily want to go but ought to be."," Rosalynn Carter"),
    Quets("There is a difference between being a leader and being a boss. Both are based on authority. A boss demands blind obedience; a leader earns his authority through understanding and trust."," Klaus Balkenhol"),
    Quets("You get in life what you have the courage to ask for."," Nancy D. Solomon"),
    Quets("In the end, it is important to remember that we cannot become what we need to be by remaining what we are."," Max De Pree"),
    Quets("A leader isn't someone who forces others to make him stronger; a leader is someone willing to give his strength to others so that they may have the strength to stand on their own.","Beth Revis"),
    Quets("Always remember, Son, the best boss is the one who bosses the least. Whether it's cattle, or horses, or men, the least government is the best government."," Ralph Moody"),
    Quets("If you really want the key to success, start by doing the opposite of what everyone else is doing.","Brad Szollose"),
    Quets("The art of leadership is saying no, not yes. It is very easy to say yes."," Tony Blair"),
    Quets("Wisdom equals knowledge plus courage. You have to not only know what to do and when to do it, but you have to also be brave enough to follow through."," Jarod Kintz"),
    Quets("In a battle between two ideas, the best one doesn't necessarily win. No, the idea that wins is the one with the most fearless heretic behind it."," Seth Godin"),
    Quets("If you want to build a ship, don't drum up the men to gather wood, divide the work, and give orders. Instead, teach them to yearn for the vast and endless sea."," Antoine de Saint-Exupery"),
    Quets("Remember, teamwork begins by building trust. And the only way to do that is to overcome our need for invulnerability."," Patrick Lencioni"),
    Quets("Leadership is an action, not a position."," Donald McGannon"),
    Quets("Surround yourself with great people; delegate authority; get out of the way."," Ronald Reagan"),
    Quets("I cannot give you a formula for success, but I can give you the formula for failure, which is: Try to please everybody."," Herbert Bayard Swope"),
    Quets("Show me the man you honor and I will know what kind of man you are."," Thomas John Carlisle"),
    Quets("A man always has two reasons for doing anything: a good reason and the real reason.","J.P. Morgan"),
    Quets("If you spend your life trying to be good at everything, you will never be great at anything."," Tom Rath"),
    Quets("Average leaders raise the bar on themselves; good leaders raise the bar for others; great leaders inspire others to raise their own bar."," Orrin Woodward"),
    Quets("Don't blow off another's candle for it won't make yours shine brighter."," Jaachynma N.E. Agu"),
    Quets("Whenever you see a successful business, someone once made a courageous decision."," Peter F. Drucker"),
    Quets("When you put together deep knowledge about a subject that intensely matters to you, charisma happens. You gain courage to share your passion, and when you do that, folks follow."," Jerry Porras"),
    Quets("People buy into the leader before they buy into the vision."," John Maxwell"),
    Quets("A good leader is a person who takes a little more than his share of the blame and a little less than his share of the credit."," John Maxwell"),
    Quets("A good plan violently executed now is better than a perfect plan executed next week."," George Patton"),
    Quets("Feeling gratitude and not expressing it is like wrapping a present and not giving it.", "William Arthur Ward"),
    Quets("Silent gratitude isn't very much to anyone."," Gertrude Stein"),
    Quets("The only people with whom you should try to get even are those who have helped you." ,"John E. Southard"),
    Quets("Keep your eyes open and try to catch people in your company doing something right, then praise them for it."," Tom Hopkins"),
    Quets("You wouldn't worry so much about what others think of you if you realized how seldom they do.","Eleanor Roosevelt"),
    Quets("Low self-confidence isn't a life sentence. Self-confidence can be learned, practiced, and mastered-just like any other skill. Once you master it, everything in your life will change for the better."," Barrie Davenport"),
    Quets("Shyness has a strange element of narcissism, a belief that how we look, how we perform, is truly important to other people."," Andre Dubus"),
    Quets("Do it or not. There is no try."," Yoda"),
    Quets("Rarely have I seen a situation where doing less than the other guy is a good strategy."," Jimmy Spithill"),
    Quets("You may have to fight a battle more than once to win it."," Margaret Thatcher"),
    Quets("The best revenge is massive success.","Frank Sinatra"),
    Quets("The question isn't who is going to let me; it's who is going to stop me."," Ayn Rand"),
    Quets("The only way to do great work is to love what you do."," Steve Jobs"),];

  Quets(this.statement,this.person);
  String  statement;
  String person;
}

